apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: aura-route
  namespace: aura
  labels:
    app: aura
spec:
  to:
    kind: Service
    name: aura-core
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
